apiVersion: v1
kind: Service
metadata:
  name: mcart-angularapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mcart-angularapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80