name: Build and Deploy Angular App to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINER_REGISTRY: prasadbhalerao
  CONTAINER_NAME: mcart-angularapp
  RESOURCE_GROUP: Mcart-RG
  CLUSTER_NAME: Mcart-AKS-Cluster
  NAMESPACE: default # Add your Kubernetes namespace

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --prod

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }} .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

      - name: Check Docker container file structure
        run: |
          docker run --rm ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }} ls -R /manifests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Change to root directory
        run: cd ${{ github.workspace }}

      - name: Debug File Paths
        run: |
          pwd
          ls -R manifests/

      - name: Replace Image Tag in Deployment
        run: |
          sed -i "s|<IMAGE_TAG>|${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}|g" manifests/deployment.yaml

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -n ${{ env.NAMESPACE }} -f manifests/deployment.yaml || exit 1

      - name: Apply Kubernetes Service
        run: |
          kubectl apply -n ${{ env.NAMESPACE }} -f manifests/service.yaml || exit 1

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }} || exit 1