name: Deploy Angular App to Azure Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_STORAGE_ACCOUNT: mcartsa # Replace with your storage account name
  AZURE_STORAGE_CONTAINER: '$web' # Use $web for static website hosting
  RESOURCE_GROUP: Mcart-RG
  INDEX_DOCUMENT: index.html # the index document
  ERROR_DOCUMENT: 404.html # the 404 error document

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --prod

      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source dist/mcart-web \
            --overwrite \
            --auth-mode login

      - name: Configure Static Website
        run: |
          az storage blob service-properties update \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --static-website \
            --index-document ${{ env.INDEX_DOCUMENT }} \
            --404-document ${{ env.ERROR_DOCUMENT }}

      - name: Get Storage Endpoint
        run: |
          echo "Storage Endpoint:"
          az storage account show \
            --name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --query "primaryEndpoints.web" \
            -o tsv